version: '3.8'

services:
  app:
    build: .
    container_name: iam-invoicer
    ports:
      - "8090:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=file:/app/data/database.sqlite
      - JWT_SECRET=iam_invoicer_secret_key_2024
      - JWT_EXPIRES_IN=24h
      - CORS_ORIGIN=*
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  migrations:
    build: .
    command: npx prisma migrate deploy && npx prisma db seed
    environment:
      - DATABASE_URL=file:/app/data/database.sqlite
    volumes:
      - ./data:/app/data